netsh wlan connect ssid=CHILESSANJOSE3 name=CHILESSANJOSE3

cmd /c START "C:\Program Files\Microsoft Office\root\Office16\MSACCESS.EXE" "\\T1000-PC\chilessanjose\BASES_DATOS\TICKETS_RAPIDOS\SISTEMAS_CHSJ\USO_INTERNO.accdb"

cmd /c START "C:\Program Files\Microsoft Office\root\Office16\MSACCESS.EXE" "\\T1000-PC\chilessanjose\BASES_DATOS\TICKETS_RAPIDOS\SISTEMAS_CHSJ\PUNTO_VENTA.accdb"

cmd /c START "C:\Program Files\Microsoft Office\root\Office16\MSACCESS.EXE" "\\T1000-PC\chilessanjose\BASES_DATOS\PRECIOS\BD_CHILES_V3.accdb"

cmd /c START "C:\Program Files\Microsoft Office\root\Office16\MSACCESS.EXE" "\\T1000-PC\chilessanjose\BASES_DATOS\ADMINISTRACION\bd_administrativa_2020.accdb"

cmd /c START "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE" "\\T1000-PC\chilessanjose\BASES_DATOS\ADMINISTRACION\EFECTIVOS_2022.xlsx"

cmd /c START "C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE" "\\T1000-PC\chilessanjose\BASES_DATOS\ADMINISTRACION\TICKETS.xlsx"

cmd /c START C:\Users\RUBEN\AppData\Local\WhatsApp\WhatsApp.exe

cmd /c "C:\Users\\RUBEN\AppData\Local\Programs\Opera\launcher.exe"

exit /b